### ISSUE TITLE
Add beginner material

### ISSUE THREAD

**Issue by kentcdodds** [nayafia/contributing-template#1]
Hi there! This looks great! I thought it may be handy to recommend people reference the material as mentioned on [makeapullrequest.com](http://makeapullrequest.com):

```
**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
```

I wasn't sure where the best place for this would be. Maybe in `Your First Contribution` or `Getting started`.

Full disclosure, that series of lessons is from me and even though it's free I make money when people watch it. But my motive is to help lower the barrier of entry to Open Source (as I believe is your motivation as well).

**Comment by nayafia** [comment]
Hi @kentcdodds! Thanks for all your amazing work on making open source friendly and welcoming.

I actually use that reference as the example (quoting from React) for how to add a resource for people who have never contributed to open source, here: https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md#bonus-points-add-a-link-to-a-resource-for-people-who-have-never-contributed-to-open-source-before

Is there another way you think would be more helpful to phrase it?

**Comment by kentcdodds** [comment]
Ah! Perfect, I must have somehow missed that bit. Thanks for this guide! I've already referenced someone who asked me for feedback to it: https://github.com/benmosher/eslint-plugin-import/pull/258#issuecomment-213566522

**Comment by techtonik** [comment]
@nayafia solving financial hurdles and helping with coordination and open source economics will make open source more human-like. It is an adaptive process. The main reason why people become grudgy in open source scene, is because maintaining your software is not only fun, but sometimes also a responsibility to deal with hard development issues, and economics doesn't support it. People turn grumpy when you need a big lump of time to solve complex issues, but have no place to meet with likeminded people, still have to maintain daily job, relationships, stable food supply as a parallel process, and no time left to maintain your software. When there is no time, you're not even able to participate in the process of changing the stuff, and this is the most depressing thing in that.
