### ISSUE TITLE
Add copyright/attribution section

### ISSUE THREAD

**Issue by abetusk** [nayafia/contributing-template#2]
Unfortunately I don't know much about this or what standard practices are but it's probably good to tell potential contributors how they'll be credited, if at all.  Will they be given credit in the README file?  What portion of their work will fall under their copyright?  If it's for a business or organization are the contributors handing over their copyright to the organization?

Wikipedia has an article on [contributor license agreements](https://en.wikipedia.org/wiki/Contributor_License_Agreement).  For reference, here are some CLAs of note:
- [Google CLA](https://cla.developers.google.com/about/google-individual?csw=1)
- [Apache Software Foundation Individual CLA](http://www.apache.org/licenses/icla.txt)
- [Apache Software Foundation Corporate CLA](http://www.apache.org/licenses/cla-corporate.txt)

Googling around produces an article by Bradley Kuhn called ["Why Your Project Doesn't Need a Contributor Licensing Agreement"](http://ebb.org/bkuhn/blog/2014/06/09/do-not-need-cla.html) so I guess there's some controversy about whether a CLA is even needed or is overkill.

Here's a link dump of potentially useful links:
- ["Why the FSF gets copyright assignments from contributors" by Eben Moglen](https://gnu.org/licenses/why-assign)
- ["What is a CLA and why do I care?" by Tony Guntharp from CLAHub](https://www.clahub.com/pages/why_cla)
- ["CLAHub - CLA's Done Right" by Tony Guntharp](http://fusion94.org/blog/2013/01/16/clahub-clas-done-right/)
- ["Contributor Licence Agreements" by Ross Gardler and Rowan Wilson from OSS Watch](http://oss-watch.ac.uk/resources/cla)
- ["Not all CLAs are equal" by Matthew Garrett](http://mjg59.dreamwidth.org/29160.html?style=light&thread=1094632)
- ["A CLA By Any Other Name" by Pamela Jones from Groklaw](http://www.groklaw.net/articlebasic.php?story=20110524120303815)
- ["When a company asks for your copyright" by Richard Stallman from the FSF](http://www.fsf.org/blogs/rms/assigning-copyright)
- ["Linus Torvalds Says All Contributor License Agreements Are Broken" by Silviu Stahie at news.softpedia.com](http://news.softpedia.com/news/Linus-Torvalds-Says-All-Contributor-License-Agreements-Are-Broken-418978.shtml)

I feel like I barely understand the issue.  Maybe it would be good enough to have something like the agreement that [StackOverflow has in place for it's Subscriber Content](http://stackexchange.com/legal)?  I don't know how this translates to source code, though.

**Comment by nayafia** [comment]
Thanks for opening up this discussion!

I mention in the template that if you do use CLAs, to explain the process to your readers, and linked to a couple examples of how projects do that. But I don't think it makes sense to take a stance beyond that for this project. As stated in the Readme, the purpose of this template is to provide a checklist for writing a guide, rather than offering guidance on any particular philosophy. I'd love to do future iterations of this that do dig into different philosophies, but think it's out of scope here.

It might be helpful to link to a resource that explains CLAs for people who are writing contributing guides so they can decide if they want to include one or not (i.e. "If you don't know what a CLA is, learn more here"). Do you (or anyone else) have a comprehensive, neutral resource to recommend? I'm thinking something like choosealicense.com but for CLAs.
